### ISSUE TITLE
Error: Cannot find module 'ethereumjs-abi'

### ISSUE THREAD

**Issue by Simoneth** [ethereumjs/ethereumjs-abi#51]
specs:

```
Win 8.1 x64
node 8.0.0
npm 5.0.0
```

script "constructor_arguments_in_abi.js"

```
var abi = require('ethereumjs-abi');
var BN = require('bn.js')

parameterTypes = ['address', 'uint256', 'uint256', 'uint256', 'uint256'];
var parameterValues = ['0x123b92c756746da9c264b6e87e7f388c404ea8b8',1507794949,1000000000000000000,32422181682280000000000,32422181682280000000000];

var encoded = abi.rawEncode(parameterTypes, parameterValues);
console.log("Encoded: \n",encoded.toString('hex'));
```

Prompt console as admin:

```
C:\projects\ethereum>node constructor_arguments_in_abi.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'ethereumjs-abi'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\ethereum\constructor_arguments_in_abi.js:
41:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
What am I doing wrong?

**Comment by Simoneth** [comment]
...and just to be more precise, path on Win to node.js is correct

**Comment by SephirothLT** [comment]
Hi, I have meet this problem too,have you solved?please help

**Comment by pinanklakhani** [comment]
How can i decode this encoded string inside Solidity smart contract?

**Comment by michellk123** [comment]
hey, did you manage to overcome this problem? and how? please HELP!!
