### ISSUE TITLE
Cannot find module 'ethereumjs-abi'

### ISSUE THREAD

**Issue by SephirothLT** [ethereumjs/ethereumjs-abi#58]
Running migration: 2_deploy_managers.js
module.js:557
    throw err;
    ^

Error: Cannot find module 'ethereumjs-abi'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

**Comment by SephirothLT** [comment]
ok，` npm install  ethereumjs-abi`  solved this problem
