### ISSUE TITLE
Decoded int exceeds width: 160 vs 256

### ISSUE THREAD

**Issue by miguelmota** [ethereumjs/ethereumjs-abi#66]
Source code:

```js
const ethabi = require('ethereumjs-abi')
const buf = Buffer.from('85f1150654584d0192059454e9dc1532d9d9cf914926406a02370cea80cf32f6', 'hex')
const res = ethabi.rawDecode(['address'], buf) // fails here
console.log(res)
```

Console output:

```bash
/Users/mota/Sandbox/debug/node_modules/ethereumjs-abi/lib/index.js:242
      throw new Error('Decoded int exceeds width: ' + parsedType.size + ' vs ' + num.bitLength())
      ^

Error: Decoded int exceeds width: 160 vs 256
    at decodeSingle (/Users/mota/Sandbox/debug/node_modules/ethereumjs-abi/lib/index.js:242:13)
    at decodeSingle (/Users/mota/Sandbox/debug/node_modules/ethereumjs-abi/lib/index.js:210:12)
    at Function.ABI.rawDecode (/Users/mota/Sandbox/debug/node_modules/ethereumjs-abi/lib/index.js:367:19)
    at Object.<anonymous> (/Users/mota/Sandbox/debug/index.js:4:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
```

Transaction data from:

https://etherscan.io/tx/0x0fc8f1cb5112c4679dfcbde54306cabecedfbfd115030252b2e3d77ed7b7da8c

```
Function: transfer(address _to, uint256 _value)

MethodID: 0xa9059cbb
[0]:  85f1150654584d0192059454e9dc1532d9d9cf914926406a02370cea80cf32f6
[1]:  00000000000000000000000000000000000000000000000000000000033dc10b
```

method ID:

transfer(address,uint256) => **a9059cbb**2ab09eb219583f4a59a5d0623ade346d962bcd4e46b11da047c9049b

**Comment by fanatid** [comment]
This happened because you pass `address` type, expected size is 160. First 12 bytes from first argument will be lost... check event logs and you will see this.
