### ISSUE TITLE
abi.solidityPack does not work with array

### ISSUE THREAD

**Issue by gonglinyuan** [ethereumjs/ethereumjs-abi#70]
```
> abi.solidityPack(['int32[]', 'bytes8', 'address'], [[0, 0], '0x123456', '0x14723a09acff6d2a60dcdf7aa4aff308fddc160c'])
TypeError: Cannot read property '1' of null
    at parseTypeN (C:\Users\gonglinyuan\node_modules\ethereumjs-abi\lib\index.js:42:42)
    at Function.ABI.solidityPack (C:\Users\gonglinyuan\node_modules\ethereumjs-abi\lib\index.js:467:14)
> abi.solidityPack(['bytes8', 'address'], ['0x123456', '0x14723a09acff6d2a60dcdf7aa4aff308fddc160c'])
<Buffer 12 34 56 00 00 00 00 00 14 72 3a 09 ac ff 6d 2a 60 dc df 7a a4 af f3 08 fd dc 16 0c>
```

As you can see, solidityPack works perfectly well when there are no array in the parameters. But with 'int32[]', it fails.

**Comment by Alonzo-Coeus** [comment]
seems to be due to the function `parseTypeN` which they use for packing ints and uints. It thinks the list/array is actually a number as the check for type is  `type.startsWith('uint')` which would obviously cause problems.
